### ISSUE TITLE
ENS-1155 Renewal of Token Expiry

### ISSUE THREAD

**Issue by nicktaras** [SmartTokenLabs/TokenScript-Templates#2]
Whilst developing the ENS-1155 solution there were issues found when trying to renew a tokens expiry, to mimic the same functionality via the ENS-721 solution.

Steps to re-create the issue:

- Change branch https://github.com/SmartTokenLabs/TokenScript-Templates/tree/feature/1155-ens
- Uncomment the TS Card "Renew" and the Svelte "Renew" route.
- Emulate the ENS-1155 TS
- Via the renew view with your wallet connected, click 'renew' with the console open

Expected error:

Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x7abaEd470E89820738B5e58874dFa7a77F9Cd44d","to":"0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85","data":"0xc475abff22bc263f964cc8eb063fab871e2501b69d210341f05969918ff6e3afd73f92060000000000000000000000000000000000000000000000000000000001e13380","accessList":null}, error={"code":-32000,"message":"execution reverted"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)

Towards investigating this issue - when re-creating this scenario with Ethers JS  the transaction can reach the wallet for confirmation.

````
const contractAddress = '0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85';

const contractABI = [
  {
    "constant": false,
    "inputs": [
      { "internalType": "uint256", "name": "id", "type": "uint256" },
      { "internalType": "uint256", "name": "duration", "type": "uint256" }
    ],
    "name": "renew",
    "outputs": [
      { "internalType": "uint256", "name": "", "type": "uint256" }
    ],
    "payable": false,
    "stateMutability": "nonpayable",
    "type": "function"
  }
];

async function renewContract() {

  var wallet = 'YOUR_WALLET_SIGNER';

  const contract = new _ethers.Contract(contractAddress, contractABI, wallet);

  const id = 'token id'; (decimal)
  const duration = 31536000n;

  try {
    const transaction = await contract.renew(id, duration, { gasLimit: 200000 });
    await transaction.wait();
    console.log('Transaction successful:', transaction.hash);
  } catch (error) {
    console.error('Transaction failed:', error.message);
  }
}

renewContract();

````

At this time, I'm unsure if this is a TS issue or if there is a misconfiguration on my side.

cc: @futantan

**Comment by micwallace** [comment]
@nicktaras There are several issues I pointed out yesterday that you have not actioned:

- This contract address is wrong. The latest version of ETHRegistarController is 0x253553366Da8546fC250F225fe3d25d0C782303b you are using an older version and I'm not sure why it's not a payable function as renewing costs ETH. I'd updated this yesterday but you created your own branch and reverted my changes. Please take care when merging. 
- Similarly, the transaction definition is incorrect. Let's compare the 721 definition:
  ```
  <ts:transaction>
	<ethereum:transaction function="renew" contract="ETHRegistrarController" as="uint">
		<ts:data>
			<ts:string ref="ensName"/>
			<ts:uint256 local-ref="renewalSeconds"/>
		</ts:data>
		<ethereum:value local-ref="renewalPrice"/>
	</ethereum:transaction>
  </ts:transaction>
  ```
  To the 1155 version:
  ```
    <ts:transaction>
	<ethereum:transaction function="renew" contract="ETHRegistrarController" as="uint">
		<ts:data>
			<ts:uint256 ref="baseENSTokenId"/>
			<ts:uint256 ref="renewalSeconds"/>
		</ts:data>
	</ethereum:transaction>
  </ts:transaction>
  ```
  
  Notice that the value is missing.

**Comment by micwallace** [comment]
@nicktaras I found out that the address (0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85) you were using is the base registrar not the ETHRegistrarController. The renew function for base registar is probably used internally through the ETHRegistarController.
