### ISSUE TITLE
Spelling error for success message shown on the dialog box when accepting friend invite for ERC721 messaging.

### ISSUE THREAD

**Issue by abhishes007** [SmartTokenLabs/TokenScript-Templates#30]
Spelling error for success message shown on the dialog box when accepting friend invite for ERC721 messaging.

Steps:
1. Load the TS for ERC721 messaging and send a friend invite to a token.
2. Accept the request.

Issue:
1. Spelling error for the word "Friendship"

<img width="1211" alt="TS-ERC721-Messaging-SpellingError" src="https://github.com/user-attachments/assets/0cba3d0c-b5b4-461b-bcdf-eb4975ad7032">

**Comment by nicktaras** [comment]
Thanks @abhishes007. This is fixed.

**Comment by abhishes007** [comment]
Issue is fixed and verified, marking the issue as closed.

![image](https://github.com/user-attachments/assets/cd5eb48a-9182-4c9c-bb4b-ef47d8b9b84a)
