### ISSUE TITLE
Admin message input field does not clear and the message says invalid date when admin message is sent.

### ISSUE THREAD

**Issue by abhishes007** [SmartTokenLabs/TokenScript-Templates#31]
Admin message input field does not clear and the message says invalid date when admin message is sent.

Steps:
1. Load the TS for ERC721 messaging and use the admin account/ contract deployer wallet.
2. Click on "Chat with Friends" and sign the request.
3. Click on Admin Account and send message.

Recording:

https://github.com/user-attachments/assets/fde2b255-4b9a-4492-9c08-2a978d129076

**Comment by nicktaras** [comment]
@abhishes007 can we close this issue now we've removed the admin feature.

**Comment by abhishes007** [comment]
Verified and the Group chat messages work as expected and the input field is cleared - marking the issue as closed.

https://github.com/user-attachments/assets/985fa246-661c-4b28-a9fc-403d157ab61c
