### ISSUE TITLE
Accept Request button does not gets disabled after the request is accepted.

### ISSUE THREAD

**Issue by abhishes007** [SmartTokenLabs/TokenScript-Templates#33]
Accept Request button does not gets disabled after the request is accepted.

Steps:
1. Visit TSViewer and click on Pepe token.
2. Click on Get Friends button and accept the request in the wallet.
3. Click on "Confirm Friends" tab and select the pending request.
4. Click on "Accept Request" button.
5. Once the request is accepted click the "Accept Request" button again.

Issue:
1. Should the button be disabled after a request is accepted? - Current behavior is showing a message on the top "You are already friends and can chat. Congratulations!"

Recording:

https://github.com/user-attachments/assets/a677ef7b-2156-48f9-a6bf-0ba047af6356

**Comment by nicktaras** [comment]
Fix added. Will deploy in next update.

**Comment by abhishes007** [comment]
Fixed and verified:

https://github.com/user-attachments/assets/b697b1c8-3dc6-4902-bd6b-27292710d148

Marking the issue as closed.
