### ISSUE TITLE
Chat bubbles color to differentiate between the sender and receiver.

### ISSUE THREAD

**Issue by abhishes007** [SmartTokenLabs/TokenScript-Templates#34]
Chat bubbles color to differentiate between the sender and receiver.

Steps:
1. Visit TSViewer and open an ERC20 token with messaging.
2. Click on "Chat with Friends" button.
3. Send texts to Friends.

Issue:
1. Different color for chat bubbles to distinguish who sent the message.

Screenshot:
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/5d52ce52-c1dc-4cff-a615-e06def9b7540">

**Comment by nicktaras** [comment]
Thanks I agree. Let's wait for Sabrina's designs to address this.

**Comment by abhishes007** [comment]
Marking this as closed, since the chat bubbles are updated for the PEPE TS.

Screenshot:
![image](https://github.com/user-attachments/assets/38a31d3a-6405-476d-aaf0-d4744b37e4e3)
