### ISSUE TITLE
Do we somehow add a refresh mechanism to load the latest chat message if the message window is open.

### ISSUE THREAD

**Issue by abhishes007** [SmartTokenLabs/TokenScript-Templates#35]
Do we somehow add a refresh mechanism to load the latest chat message if the message window is open.

Steps:
1. Visit TS viewer and open the messaging for an ERC20 token.
2. Send a message from one wallet to another.
3. Receive a reply from the other wallet.

Issue:
1. Currently to retrieve the latest message user needs to go back and forth if the message window is open - For making the messaging seamless do we need a refresh mechanism?

Recording:

https://github.com/user-attachments/assets/7a048697-6e15-47b6-96e2-51a586762a00

**Comment by nicktaras** [comment]
GP @abhishes007 - I've added labels to this issue, for us to add a refresh button to both the ERC-20 and ERC-721 chat service.

**Comment by nicktaras** [comment]
Let's see what we can do here. 

The ideal solution would be for use to use websockets to make it a realtime chat app. For an initial update, I'll have a look at the timers and see if we can speed up the requests to get the latest msgs faster than current.

**Comment by nicktaras** [comment]
Fix added here to increase the message request speed to once each 5 seconds.

**Comment by abhishes007** [comment]
Verified and marking this as closed as the new messages populate quickly when the chat window is open:

https://github.com/user-attachments/assets/31e02be0-ce9b-4f88-8e8b-b2faf2403415
