### ISSUE TITLE
Latest sent messages are sometimes not shown at all till few more messages are sent.

### ISSUE THREAD

**Issue by abhishes007** [SmartTokenLabs/TokenScript-Templates#36]
Latest sent messages are sometimes not shown at all till few more messages are sent.

Steps:
1. Run local deployment for Pepe TS.
2. Click on "Chat with Friends" button and sign the message in the wallet.
3. Send messages.

Issues:
1. It seems sometimes the sent messages are not loading or shown in the chat unless user sends more messages - Could this be because I am running a local deployment?

Recording:

https://github.com/user-attachments/assets/a922a5ed-4556-443c-8fc8-369f16a22c41

**Comment by nicktaras** [comment]
Thanks @abhishes007, I'll take a look at this.

**Comment by nicktaras** [comment]
Fix added to branch.

**Comment by abhishes007** [comment]
Fixed and verified:


https://github.com/user-attachments/assets/95a3b6a4-35a2-49f8-b0bd-1d1328f75774

Marking the issue as closed
