### ISSUE TITLE
Value shown in ETH and USD in info tab is 0.

### ISSUE THREAD

**Issue by abhishes007** [SmartTokenLabs/TokenScript-Templates#37]
Value shown in ETH and USD in info tab is 0.

Steps:
1. Build and deploy Pepe TS locally.
2. Connect a wallet with the test token.
3. Click on Info button.

Issue:
1. Values for ETH and USD are shown as "0"

Recording:

https://github.com/user-attachments/assets/e74258da-07e9-4ee3-91c4-1df199972391

**Comment by nicktaras** [comment]
I see. The values shown are all correct, however these fields will show 0 if you the end user doesn't have much PEPE:

- Value ETH
- Value USD

I suggest we hide the value information when the value is 0 and also the USD price of PEPE which will always be below 0.

Example with changes (I'll push this for review):

<img width="533" alt="Screenshot 2024-09-11 at 9 05 47 PM" src="https://github.com/user-attachments/assets/4d6652ae-4c95-45a9-8244-e605b0c11bf3">

cc: @abhishes007

**Comment by nicktaras** [comment]
Fix added to PEPE branch version.

**Comment by abhishes007** [comment]
Verified:

I agree if the value is 0 because of the low amount of tokens and the price of the token we can hide it and just show the current fix.

![image](https://github.com/user-attachments/assets/936229b6-93ca-4f25-938b-3c8af03082ea)

Marking this as closed.
