### ISSUE TITLE
"Failed to invite friend" message shown on UI even when the invite was sent successfully.

### ISSUE THREAD

**Issue by abhishes007** [SmartTokenLabs/TokenScript-Templates#38]
"Failed to invite friend" message shown on UI even when the invite was sent successfully.

Steps:
1. Load Pepe TS in TS viewer.
2. Connect a wallet with Test Token.
3. Send an invite to Friend wallet.

Issue:
1. "Failed to invite friend" message shown on UI even when the invite was sent successfully.

Recording:

https://github.com/user-attachments/assets/28f132a7-e014-49be-8f8a-3a72cf3314e5

**Comment by abhishes007** [comment]
Also the same message appears when a Friend request is accepted.

![image](https://github.com/user-attachments/assets/3eb05818-6566-421e-a20e-f31346db3b31)

**Comment by nicktaras** [comment]
Thanks @abhishes007 I'll fix this.

**Comment by nicktaras** [comment]
Fix added to PEPE branch version.

**Comment by abhishes007** [comment]
Fixed and verified: Message is removed: Marking the issue as closed.


https://github.com/user-attachments/assets/386b75b3-4dd5-4cb2-95e8-c5110a0fc90a
