### ISSUE TITLE
On Android + AlphaWallet, the signing request for session is not received.

### ISSUE THREAD

**Issue by abhishes007** [SmartTokenLabs/TokenScript-Templates#39]
[Sporadic] On Android + AlphaWallet, the signing request for session is not received.

Steps:
1. Load Pepe TS on TS viewer on Android + Chrome device.
2. Connect AlphaWallet
3. Click on "Get Friends" and "Chat with Friends" buttons and observe the signing requests.

Issue:
1. Sometimes the singing request for secure session is received and sometimes it is not.

Recording: Here we can see I got a spam of 4 requests all together at the start and then later when I re-tried I did not receive any signing request.

https://github.com/user-attachments/assets/54090eab-f150-4900-872f-2185d82d9ed8

**Comment by abhishes007** [comment]
Just to add:
Though sporadic it has happened quite often with AlphaWallet, I tried the same with Metamask on Android and iPhone + AlphaWallet and did not see any issue, so this is specific to Android + AlphaWallet.

**Comment by hboon** [comment]
If it's only with AlphaWallet, it would be low priority.

**Comment by nicktaras** [comment]
On the TS side, I think the best option we have is to slow the requests coming through. Where some appear to be too fast for wallets to pick up and action.

I'll also look to stop the spam requests - I had 650 the other day via MetaMask (from leaving my machine running).

I'll try this to see if it helps. cc: @hboon, @abhishes007

**Comment by nicktaras** [comment]
Added logic to help reduce the sig requests. Can we re-check to see if this is fixed.

**Comment by abhishes007** [comment]
This still doesn't work for Android + AlphaWallet, I feel the issue is more with Wallet Connect + AlphaWallet not sending the request from TS viewer.
It works well for other wallets like imToken and Metamask.

Recording: 

Android + Chrome + AlphaWallet
https://github.com/user-attachments/assets/2a29e123-83cd-4b5a-8b19-fe73eee43f99

Android + Chrome + imToken

https://github.com/user-attachments/assets/33072c00-a29f-4bbd-b843-81c1e0e67d5b

I think we should just let this be if fixing this is too time consuming since AlphaWallet is not a priority.

cc: @nicktaras

**Comment by abhishes007** [comment]
After discussion with Nick, we have decided not to address this atm and wait to see if we get user reports for the issue and then invest time on it.

cc: @nicktaras
