### ISSUE TITLE
On Android + Edge when clicking the send message button, sometimes the message is not sent and the input field gets scrolled to the bottom.

### ISSUE THREAD

**Issue by abhishes007** [SmartTokenLabs/TokenScript-Templates#40]
On Android + Edge when clicking the send message button, sometimes the message is not sent and the input field gets scrolled to the bottom.

Steps:
1. Load Pepe TS File on Android + Edge browser.
2. Connect a wallet.
3. Click on "Chat with Friends" and send messages.

Issue:
1. Sometimes the message is not actually sent and the input field scrolls to the bottom.

Recording:

https://github.com/user-attachments/assets/1857f6ab-8ee5-4992-979b-f1b36c6e2b13

**Comment by nicktaras** [comment]
Agree. There's a timer that triggers each minute force scrolling the end user to the most recent message. 

I'll make some changes to this logic so the user is free to navigate the messages.

I'll take a look into the issue when the message is not sent - I'd not seen this on desktop / IOS during dev.

**Comment by abhishes007** [comment]
I did not observe this on Desktop or iOS either. Even on Android it happened only with Edge.

**Comment by nicktaras** [comment]
I've removed the auto scroll and replaced this with a button users can click to go to the latest messages. This might help fix this edge issue.

**Comment by abhishes007** [comment]
This is very specific to Android + Edge.
I tried it on two different devices and its more related to Edge + Keyboard being used on Android.
On one device the TS window scrolls after message is typed and send key is hit.
On other device the TS window text box is already scrolled to bottom when typing the message.


https://github.com/user-attachments/assets/f3e1927d-f726-42db-a704-27881a07631b


https://github.com/user-attachments/assets/92d8e9ed-13c9-4f19-b3ea-cd2e3915bc82

@nicktaras - We can ignore this I feel and not fix it, since user can always scroll to the bottom and send the text on second go. If we decide to not handle this please mark the issue as closed.

**Comment by abhishes007** [comment]
After discussion with Nick, we have decided not to address this atm and wait to see if we get user reports for the issue and then invest time on it.

cc: @nicktaras
